function Player_PlayingState_updateInventory(player: player):
  # Getting player information
  set {_team} to {game::player::%{_player}%::team}
  if {_team} is not set:
    stop

  # Getting team shots
  set {_availableShots} to {game::team::%{_team}%::availableShots}
  if {_availableShots} > 0:
    # This team has available shots
    set {_item} to player head named "&7%{_availableShots}%/2 &fВыстрелов доступно"
    
    if {_availableShots} is 1:
      add "{SkullOwner:{Id:""cc580a79-3444-4a8a-a236-ffb3a4e584fc"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2E1MTZmYmFlMTYwNThmMjUxYWVmOWE2OGQzMDc4NTQ5ZjQ4ZjZkNWI2ODNmMTljZjVhMTc0NTIxN2Q3MmNjIn19fQ==""}]}}}" to item-nbt of {_item}
    else if {_availableShots} is 2:
      add "{SkullOwner:{Id:""76e59870-f172-4a44-80b5-96f67058ce9e"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDY5OGFkZDM5Y2Y5ZTRlYTkyZDQyZmFkZWZkZWMzYmU4YTdkYWZhMTFmYjM1OWRlNzUyZTlmNTRhZWNlZGM5YSJ9fX0=""}]}}}" to item-nbt of {_item}
  else:
    set {_item} to player head named "&cx &fНет доступных выстрелов"
    add "{SkullOwner:{Id:""5ecfabf0-5253-47b0-a44d-9a0c924081b9"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ==""}]}}}" to item-nbt of {_item}

  if {game::player::%{_player}%::isShooting} is true:
    loop numbers from 0 to 8:
      set slot loop-value of {_player}'s inventory to bow

    set slot 9 of {_player}'s inventory to arrow
  else:
    loop numbers from 0 to 8:
      set slot loop-value of {_player}'s inventory to {_item}